# Generated by Django 4.0.2 on 2022-02-06 03:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_person_shift_shift_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='shift_id',
            field=models.CharField(default=uuid.uuid4, max_length=100),
        ),
    ]
