# Generated by Django 4.0.2 on 2022-02-06 03:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_shift_shift_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sch_Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sch_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('sch_to', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='shift',
            name='sch_from',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='sch_to',
        ),
        migrations.AddField(
            model_name='shift',
            name='sch_time_range',
            field=models.ManyToManyField(to='main.Sch_Time'),
        ),
    ]
