# Generated by Django 4.0.2 on 2022-02-06 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_sch_time_remove_shift_sch_from_remove_shift_sch_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='sch_activity',
        ),
        migrations.AddField(
            model_name='sch_time',
            name='sch_activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sch_activity', to='main.activities'),
        ),
    ]
