# Generated by Django 4.0.2 on 2022-02-06 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_shift_sch_activity_sch_time_sch_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sch_time',
            name='sch_from',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='sch_time',
            name='sch_to',
            field=models.TimeField(),
        ),
    ]
