# Generated by Django 4.0.2 on 2022-02-06 04:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_sch_time_sch_from_alter_sch_time_sch_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
