# Generated by Django 4.0.2 on 2022-02-06 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_shift_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='time_len',
            field=models.IntegerField(default=0),
        ),
    ]
